WhatsUpV2/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WhatsUpV2.Interfaces;
using WhatsUpV2.Repositories;

namespace WhatsUpV2.Controllers
{
    public class ChatsController : ControllerBase
    {
        private readonly IChatRepository _chatRepository = new ChatRepository();
        private readonly IMessageRepository _messageRepository = new MessageRepository();

        /// <summary>
        ///     List all of the chats
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await _chatRepository.GetChats(GetSessionUserName()));
        }

        /// <summary>
        ///     Display a chat
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public async Task<ActionResult> Chat(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var chat = await _chatRepository.Get(id.Value);
            if (chat == null)
            {
                return HttpNotFound();
            }

            // Check if user is allowed to view chat
            var username = GetSessionUserName();
            if (chat.UserA != username && chat.UserB != username)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            return View(await _messageRepository.GetChatMessages(id.Value));
        }

        /// <summary>
        ///     Send a message to a chat
        /// </summary>
        /// <param name="chatId"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Send(int chatId)
        {
            await _messageRepository.Send(chatId, GetSessionUserName(), Request.Form["messageText"]);
            return RedirectToAction("Chat", new {id = chatId});
        }
    }
}

WhatsUpV2/Views/Chats/Chat.cshtml
@model IEnumerable<WhatsUpV2.EFModels.Message>

@{
    ViewBag.Title = "Chat";
}

<h2>Messages</h2>

@using (Html.BeginForm("Send", "Chats", new { chatId = ViewContext.RouteData.Values["id"] }))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.Editor("messageText", new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <input type="submit" value="Send" class="btn btn-default" />
        </div>
    </div>
}

@foreach (var item in Model)
{

    <p>
        <b>@item.Sender</b>:@item.Text
    </p>
}

WhatsUpV2/Views/Chats/Index.cshtml
@model IEnumerable<WhatsUpV2.EFModels.Chat>

@{
    ViewBag.Title = "View";
}

<h2>Chats</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserB)
        </th>
        <th>
            @Html.DisplayName("message")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserB)
        </td>
        <td>
            @{
                var recentMsg = item.GetMostRecentMessage();
            }
            @Html.DisplayFor(modelItem => recentMsg)
        </td>
        <td>
            @Html.ActionLink("View chat", "Chat", new { id=item.Id })
        </td>
    </tr>
}

</table>